# MI Knowledge Hub - Jekyll Configuration

# Site settings
title: "MI Knowledge Hub"
description: "マテリアルズ・インフォマティクス（Materials Informatics）の包括的な学習プラットフォーム"
baseurl: "/AI_Homepage/MI"
url: "https://yusukehashimotolab.github.io"

# Language
lang: ja

# Build settings
markdown: kramdown
kramdown:
  input: GFM  # GitHub Flavored Markdown
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  content:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: "content"
      type: "content"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .venv
  - venv
  - __pycache__
  - "*.pyc"
  - .git
  - .gitignore
  - .DS_Store
  - README.md
  - requirements.txt
  - tools
  - reviews
  - claudedocs
  - notebooks
  - .claude

# Include
include:
  - "_pages"

# Markdown extensions
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Sass
sass:
  sass_dir: assets/css
  style: compressed

# SEO
twitter:
  username: # あれば追加
  card: summary_large_image

# Analytics (optional)
# google_analytics: UA-XXXXXXXX-X
